services:
  postgres:
    image: postgres:16.4
    container_name: postgres_db
    environment:
      POSTGRES_USER: notorium
      POSTGRES_PASSWORD: notorium
      POSTGRES_DB: notorium
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
